from __future__ import annotations

EXCEL_OFFICIAL_CONTRACT_VERSION = 1

REQUIRED_INSTITUTIONAL_SHEETS: tuple[str, ...] = (
    "LEIA-ME",
    "PARAMETROS",
    "PAINEL",
    "QUALIDADE E GOVERNANÇA",
    "MATRIZ",
    "PLANO_DE_ACAO",
)

STANDARD_TECHNICAL_SHEETS: tuple[str, ...] = (
    "METAS",
    "INDICADORES",
    "CALC",
    "LISTAS DE APOIO",
)

OPTIONAL_TECHNICAL_SHEETS: tuple[str, ...] = (
    "DIM_PERIODO",
    "DIM_MES",
)

ALL_RESERVED_SHEETS: frozenset[str] = frozenset(
    REQUIRED_INSTITUTIONAL_SHEETS + STANDARD_TECHNICAL_SHEETS + OPTIONAL_TECHNICAL_SHEETS
)

TECHNICAL_LAYER_NOTICE = "CAMADA TÉCNICA — NÃO ALTERAR"
