-- Names and periodicities from the UNIVC v3 indicator matrix. Formulas/sources can be enriched progressively.
insert into public.indicator_definitions(code,directorate_code,name,periodicity) values
('REI-01','REITORIA','Índice de Aderência à Rotina de Dados','Mensal'),('REI-02','REITORIA','NPS da Metodologia TTL','Bimestral'),('REI-03','REITORIA','Cobertura e Execução dos Planos de Ação','Mensal'),
('DPE-01','DPE','Resultado Operacional','Mensal'),('DPE-02','DPE','Custo por Aluno Ativo, por Curso','Mensal'),('DPE-03','DPE','Taxa de Inadimplência','Mensal'),('DPE-04','DPE','Execução Orçamentária','Mensal'),('DPE-05','DPE','Saldo Operacional de Caixa','Mensal'),('DPE-06','DPE','Custo de Folha sobre Receita','Mensal'),('DPE-07','DPE','Alunos por Módulo e por Turma','Mensal'),('DPE-08','DPE','Taxa de Ocupação de Vagas Ofertadas','Mensal / fechamento semestral'),
('DTNH-01','DTNH','NPS Discente da Área','Bimestral'),('DTNH-02','DTNH','Matrículas Ativas por Curso','Mensal'),('DTNH-03','DTNH','Frequência Média Discente','Mensal'),('DTNH-04','DTNH','Taxa de Reprovação','Bimestral'),('DTNH-05','DTNH','Cumprimento de Registros Acadêmicos no Prazo','Mensal'),('DTNH-06','DTNH','NPS Docente','Semestral'),('DTNH-07','DTNH','Adequação da Titulação do Corpo Docente','Semestral'),('DTNH-08','DTNH','Produção em Pesquisa e Extensão','Semestral'),
('DCS-01','DCS','NPS Discente da Área','Bimestral'),('DCS-02','DCS','Matrículas Ativas por Curso','Mensal'),('DCS-03','DCS','Frequência Média Discente','Mensal'),('DCS-04','DCS','Taxa de Reprovação','Bimestral'),('DCS-05','DCS','Cumprimento de Registros Acadêmicos no Prazo','Mensal'),('DCS-06','DCS','NPS Docente','Semestral'),('DCS-07','DCS','Adequação da Titulação do Corpo Docente','Semestral'),('DCS-08','DCS','Produção em Pesquisa e Extensão','Semestral'),
('DEAD-01','DEAD','NPS Discente da Área','Bimestral'),('DEAD-02','DEAD','Matrículas Ativas por Curso','Mensal'),('DEAD-03','DEAD','Frequência Média Discente','Mensal'),('DEAD-04','DEAD','Taxa de Reprovação','Bimestral'),('DEAD-05','DEAD','Cumprimento de Registros Acadêmicos no Prazo','Mensal'),('DEAD-06','DEAD','NPS Docente','Semestral'),('DEAD-07','DEAD','Adequação da Titulação do Corpo Docente','Semestral'),('DEAD-08','DEAD','Produção em Pesquisa e Extensão','Semestral'),('DEAD-09','DEAD','Vazão de Alunos — Funil de Captação','Mensal'),('DEAD-10','DEAD','Estágio dos Polos em Abertura','Mensal'),('DEAD-11','DEAD','Performance dos Polos em Operação','Mensal'),('DEAD-12','DEAD','Custo de Aquisição por Aluno (CAC)','Mensal'),('DEAD-13','DEAD','Engajamento no Ambiente Virtual (AVA)','Mensal'),('DEAD-14','DEAD','Geração de Leads por Canal','Mensal'),
('DADM-01','DADM','Taxa de Evasão','Mensal'),('DADM-02','DADM','Taxa de Ensalamento','Mensal'),('DADM-03','DADM','Prazo Médio de Atendimento de Compras','Mensal'),('DADM-04','DADM','Economia Obtida em Compras','Mensal'),('DADM-05','DADM','Atendimento de Chamados de Infraestrutura e TI no Prazo','Mensal'),('DADM-06','DADM','Absenteísmo e Rotatividade de Pessoal','Mensal'),('DADM-07','DADM','Regularidade Documental e Contratual','Mensal'),('DADM-08','DADM','Score de Clima e Cultura Organizacional','Semestral'),('DADM-09','DADM','Custo Administrativo por Aluno','Mensal'),('DADM-10','DADM','Eficiência das Despesas de Infraestrutura','Mensal'),
('DM-01','DM','Ocupação de Vagas do Mestrado','Mensal / fechamento por turma'),('DM-02','DM','Vazão de Candidatos do Processo Seletivo','Por edital / acompanhamento mensal'),('DM-03','DM','Inadimplência do Programa','Mensal'),('DM-04','DM','Produção Intelectual do Corpo Docente Permanente','Trimestral'),('DM-05','DM','Taxa de Titulação no Prazo','Semestral'),('DM-06','DM','Resultado Financeiro do Programa','Mensal'),('DM-07','DM','Orientandos por Docente Permanente','Semestral'),('DM-08','DM','Satisfação dos Mestrandos (NPS)','Semestral'),('DM-09','DM','Aderência aos Critérios de Avaliação Externa','Trimestral')
on conflict(code) do update set name=excluded.name,periodicity=excluded.periodicity,directorate_code=excluded.directorate_code;

insert into public.indicator_schedules(indicator_code,reference_grain,due_business_day,collection_window_start_business_day)
select code,
  case when periodicity ilike '%semestral%' then 'semester' when periodicity ilike '%trimestral%' then 'quarter' when periodicity ilike '%bimestral%' then 'bimonth' else 'month' end,
  5,1
from public.indicator_definitions
on conflict(indicator_code) do nothing;
